[build]
publish = ".vitepress/dist"

[build.environment]
NODE_VERSION = "20"

[context.deploy-preview.environment]
command = "pnpm docs:build"

[context.production]
command = "pnpm docs:build --base='/docs/'"
